- name : Variable Play Level
  hosts : localhost
  become: yes
  vars:
    Course: Devops
    Trainer: Siva
    Learner: chandu
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Learner is {{Learner}}}"